# Generated by Django 4.2.5 on 2023-09-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carrinho_produtos_carrinho_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(related_name='carrinho', to='api.produto'),
        ),
    ]
